# Generated by Django 3.1.5 on 2021-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(max_length=400, upload_to='articulos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now=True, max_length=400, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, max_length=400, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.DeleteModel(
            name='articulo',
        ),
    ]
