# Generated by Django 3.1.5 on 2021-02-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWebApp', '0005_auto_20210128_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Posts',
        ),
    ]
