# Generated by Django 3.1.5 on 2021-02-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWebApp', '0006_auto_20210201_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
