# Generated by Django 3.1.5 on 2021-02-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoWebApp', '0007_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
